 apiVersion: v2
 name: applications
 version: 0.1.0
 description: Primary application set
 type: application
 maintainers:
   - name: Nick Speare
     email: nick@example.com
 dependencies:
   - name: nginx
     version: "0.0.1"
   - name: alpine
     version: "0.0.2"
