spec:
  destination:
    server: https://kubernetes.default.svc
argo_apps:
  alpine:
    repoURL: https://github.com/e-volusian/argo-apps/alpine
    namespace: alpine
    syncPolicy: automated
  nginx:
    repoURL: https://github.com/e-volusian/argo-apps/nginx
    namespace: nginx
    syncPolicy: automated