 apiVersion: v2
 name: alpine
 version: 0.1.0
 # description: A Helm chart for deploying my application
 appVersion: "1.0.0"
 type: application
 keywords:
   - helm
   - chart
 maintainers:
   - name: John Doe
     email: john.doe@example.com
 sources:
   - https://github.com/e-volusian/argo-apps/alpine
